/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscarModulo.java
 *
 * Created on Sep 7, 2011, 12:13:13 AM
 */

package interfaces;

import Conexion.GestorBD;
import Entidades.Modulo;
import com.mysql.jdbc.ResultSet;
import java.sql.Date;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author General
 */
public class BuscarModulo extends javax.swing.JDialog {
    //JDialog jdiag = new JDialog();
    GestorBD ser;
    Modulo modulo;
    String dato;
    private DefaultTableModel modelo;
    /** Creates new form BuscarModulo */
    public BuscarModulo(ModificarModulo parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CargarModulo();
    }

    BuscarModulo(JDialog jdiag, boolean modal) {
        super(jdiag, modal);
        initComponents();
        CargarModulo();
    }
    
    BuscarModulo(AsignarModulo aThis, boolean b) {
        super(aThis,b);
        initComponents();
        CargarModulo();
    }

    BuscarModulo(VerModulo aThis, boolean b) {
        super(aThis,b);
        initComponents();
        CargarModulo();
    }

    BuscarModulo(EstadoModulo aThis, boolean b) {
        super(aThis,b);
        initComponents();
        CargarModuloEstado();
    }

    BuscarModulo(ModificarAsignacion aThis, boolean b) {
        super(aThis,b);
        initComponents();
        CargarModulo();
    }

    BuscarModulo(ProgramarDescuento aThis, boolean b) {
        super(aThis,b);
        initComponents();
        CargarModulo();
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BuscarDato = new javax.swing.JTextField();
        BotonAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaElegirModulo = new javax.swing.JTable();
        BotonEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Modulo");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Modulo");

        BuscarDato.setFont(new java.awt.Font("Tahoma", 0, 18));

        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        TablaElegirModulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIVEL", "SUBNIVEL", "DESTINADO A:", "TIPO MODULO", "COSTO", "IdModulo", "Cantidad Clases", "Estado", "COSTO LIBRO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaElegirModulo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaElegirModulo);
        TablaElegirModulo.getColumnModel().getColumn(0).setResizable(false);
        TablaElegirModulo.getColumnModel().getColumn(1).setResizable(false);
        TablaElegirModulo.getColumnModel().getColumn(2).setResizable(false);
        TablaElegirModulo.getColumnModel().getColumn(3).setResizable(false);
        TablaElegirModulo.getColumnModel().getColumn(4).setResizable(false);
        TablaElegirModulo.getColumnModel().getColumn(5).setResizable(false);
        TablaElegirModulo.getColumnModel().getColumn(6).setResizable(false);
        TablaElegirModulo.getColumnModel().getColumn(7).setResizable(false);
        TablaElegirModulo.getColumnModel().getColumn(8).setResizable(false);

        BotonEditar.setText("Elegir");
        BotonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(BuscarDato, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(BotonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(BotonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addComponent(jButton2)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BuscarDato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(BotonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(BotonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
       int fila=-1;
       fila = TablaElegirModulo.getSelectedRow();
        if(fila==-1){
             JOptionPane.showMessageDialog(null,"no eligio ninguna fila","Error de Datos",JOptionPane.INFORMATION_MESSAGE) ;
            
        }else{

        
        //columna = jTable1.getSelectedColumn();
        modulo.setNivel(String.valueOf(TablaElegirModulo.getValueAt(fila,0)));
        modulo.setsubNivel(String.valueOf(TablaElegirModulo.getValueAt(fila,1)));
        modulo.settipo(String.valueOf(TablaElegirModulo.getValueAt(fila, 2)));
        modulo.setTipoModulo(String.valueOf(TablaElegirModulo.getValueAt(fila, 3)));
           float valo=(Float) TablaElegirModulo.getValueAt(fila, 4);
        modulo.setCosto(valo);
        int pk=(Integer)(TablaElegirModulo.getValueAt(fila, 5));
        modulo.setCIModulo(pk);
        int cant=(Integer)(TablaElegirModulo.getValueAt(fila,6));
        modulo.setcantidadClases(cant);
        String aux=String.valueOf(TablaElegirModulo.getValueAt(fila, 7));
        if(aux.equals("activo"))
            modulo.setEstado(1);
        else
            modulo.setEstado(0);
        dispose();
        }
        // TODO add your handling code here:
}//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
dato = BuscarDato.getText();
     if(dato.equals("")){
         CargarModulo();
     }else{
      ser = new GestorBD();
      ser.getConnection();
      try{

                     ResultSet resultad;
            //if(dato.equals(" "))
            //{
            dato ="SELECT * FROM modulo where nivel like'%"+dato+"%' or tipoModulo like'%"+dato+"%' or tipo like '%"+dato+"%'";
      resultad=  ser.consulta(dato);
      //ResultSetMetaData rsmd = resultad.getRow()


      while(resultad.next())
      {

             modulo.setCIModulo(resultad.getInt(1));
            modulo.settipo(resultad.getString(2));
            modulo.setNivel(resultad.getString(3));
            modulo.setsubNivel(resultad.getString(4));
            modulo.setcantidadClases(resultad.getInt(5));
            modulo.setCosto(resultad.getFloat(6));
            modulo.setTipoModulo(resultad.getString(7));
            /*Date inicio= resultad.getDate(8);
            modulo.setfechaInicio(String.valueOf(inicio.getYear()+1900)+"-"+String.valueOf(inicio.getMonth()+1)+"-"+String.valueOf(inicio.getDate()));
            Date finalfecha =resultad.getDate(9);
            modulo.setfechaFin(String.valueOf(finalfecha.getYear()+1900)+"-"+String.valueOf(finalfecha.getMonth()+1)+"-"+String.valueOf(finalfecha.getDate()));
*/
         Object[] dat = new Object[9];
         dat[0]= modulo.getNivel();
         dat[1]= modulo.getsubNivel();
         dat[2]= modulo.gettipo();
         dat[3]= modulo.getTipoModulo();
         //String da ="SELECT * FROM proveedor where pk_proveedor='"+entidadcompra.getCodigoProveedor()+"'";
      //resultad=  ser.ConsultarDatosTabla(da);

         dat[4]= modulo.getCosto();
         dat[5]= modulo.idModulo();
         dat[6]= modulo.getcantidadClases();



        LimpiarTabla();

        RecibirTabla(dat);
        BuscarDato.setText("");
      }
         }catch(SQLException e)
      {
          System.out.println("no pudo recuperar resultado");
      }
     }
        // TODO add your handling code here:
}//GEN-LAST:event_BotonAceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

   public void RecibirTabla(Object[] tabla)
    {

        modelo = (DefaultTableModel) TablaElegirModulo.getModel();

         Object[] dat =tabla;

         modelo.addRow(dat);
    }
    public void LimpiarTabla()
    {
        modelo = (DefaultTableModel) TablaElegirModulo.getModel();
        int a =modelo.getRowCount()-1;

        for(int i=a; i>=1;i--)
        {

        modelo.removeRow(i );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JTextField BuscarDato;
    private javax.swing.JTable TablaElegirModulo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void CargarModulo() {
        ser=new GestorBD();
        modulo=new Modulo();


            ser.getConnection();
      try{

                     ResultSet resultad;
            //if(dato.equals(" "))
            //{
            dato ="SELECT * FROM modulo";
      resultad=  ser.consulta(dato);
      //ResultSetMetaData rsmd = resultad.getRow()


      while(resultad.next())
      {
            modulo.setCIModulo(resultad.getInt(1));
            modulo.settipo(resultad.getString(2));
            modulo.setNivel(resultad.getString(3));
            modulo.setsubNivel(resultad.getString(4));
            modulo.setcantidadClases(resultad.getInt(5));
            modulo.setCosto(resultad.getFloat(6));
            modulo.setTipoModulo(resultad.getString(7));
            modulo.setEstado(resultad.getInt(8));
            modulo.setCostoLibro(resultad.getFloat(9));
            //Date inicio= resultad.getDate(8);
            //modulo.setfechaInicio(String.valueOf(inicio.getYear()+1900)+"-"+String.valueOf(inicio.getMonth()+1)+"-"+String.valueOf(inicio.getDate()));
            //Date finalfecha =resultad.getDate(9);
            //modulo.setfechaFin(String.valueOf(finalfecha.getYear()+1900)+"-"+String.valueOf(finalfecha.getMonth()+1)+"-"+String.valueOf(finalfecha.getDate()));

         Object[] dat = new Object[10];
         dat[0]= modulo.getNivel();
         dat[1]= modulo.getsubNivel();
         dat[2]= modulo.gettipo();
         dat[3]= modulo.getTipoModulo();
         dat[4]= modulo.getCosto();
         dat[5]= modulo.idModulo();
         dat[6]= modulo.getcantidadClases();
         String estado;
         if(modulo.getEstado()==1)
             estado="activo";
         else
             estado="inactivo";

         dat[7]=estado;
         dat[8]=modulo.getCostoLibro();
         if(modulo.getEstado()==1)
            RecibirTabla(dat);
         
      }
         }catch(SQLException e)
      {
          System.out.println("no pudo recuperar resultado");
      }
    }

    private void CargarModuloEstado() {
        ser=new GestorBD();
        modulo=new Modulo();


            ser.getConnection();
      try{

                     ResultSet resultad;
            //if(dato.equals(" "))
            //{
            dato ="SELECT * FROM modulo";
      resultad=  ser.consulta(dato);
      //ResultSetMetaData rsmd = resultad.getRow()


      while(resultad.next())
      {
            modulo.setCIModulo(resultad.getInt(1));
            modulo.settipo(resultad.getString(2));
            modulo.setNivel(resultad.getString(3));
            modulo.setsubNivel(resultad.getString(4));
            modulo.setcantidadClases(resultad.getInt(5));
            modulo.setCosto(resultad.getFloat(6));
            modulo.setTipoModulo(resultad.getString(7));
            modulo.setEstado(resultad.getInt(8));
            modulo.setCostoLibro(resultad.getInt(9));
            //Date inicio= resultad.getDate(8);
            //modulo.setfechaInicio(String.valueOf(inicio.getYear()+1900)+"-"+String.valueOf(inicio.getMonth()+1)+"-"+String.valueOf(inicio.getDate()));
            //Date finalfecha =resultad.getDate(9);
            //modulo.setfechaFin(String.valueOf(finalfecha.getYear()+1900)+"-"+String.valueOf(finalfecha.getMonth()+1)+"-"+String.valueOf(finalfecha.getDate()));

         Object[] dat = new Object[10];
         dat[0]= modulo.getNivel();
         dat[1]= modulo.getsubNivel();
         dat[2]= modulo.gettipo();
         dat[3]= modulo.getTipoModulo();
         dat[4]= modulo.getCosto();
         dat[5]= modulo.idModulo();
         dat[6]= modulo.getcantidadClases();
         String estado;
         if(modulo.getEstado()==1)
             estado="activo";
         else
             estado="inactivo";
         dat[7]=estado;
         dat[8]=modulo.getCostoLibro();





         RecibirTabla(dat);
      }
         }catch(SQLException e)
      {
          System.out.println("no pudo recuperar resultado");
      }
    }
}
