/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificarProfesor.java
 *
 * Created on Sep 6, 2011, 10:50:18 PM
 */

package interfaces;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author General
 */
public class ModificarProfesor extends javax.swing.JDialog {

    /** Creates new form ModificarProfesor */
    public ModificarProfesor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailCliente = new JTextField(40);
 EmailCliente.setDocument(new JTextFieldLimit(40));
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ApellidoMaterno = new JTextField(15);
        ApellidoMaterno.setDocument(new JTextFieldLimit(15));
        CelularCliente = new JTextField(8);
      CelularCliente.setDocument(new JTextFieldLimit(8));
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ApellidoPaterno = new  JTextField(15);
        ApellidoPaterno.setDocument(new JTextFieldLimit(15));
        jSeparator1 = new javax.swing.JSeparator();
        TelefonoCliente = new JTextField(7);
      TelefonoCliente.setDocument(new JTextFieldLimit(7));
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        NombreCliente = new JTextField(15);
      NombreCliente.setDocument(new JTextFieldLimit(15));
        CarnetCliente = new JTextField(10);
      CarnetCliente.setDocument(new JTextFieldLimit(9));
        DireccionCliente = new JTextField(40);
      DireccionCliente.setDocument(new JTextFieldLimit(40));
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Profesor");

        EmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailClienteActionPerformed(evt);
            }
        });
        EmailCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailClienteKeyTyped(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Harrington", 0, 18));
        jLabel4.setText("telefono");

        ApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ApellidoMaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoMaternoKeyTyped(evt);
            }
        });

        CelularCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CelularClienteKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Harrington", 0, 18));
        jLabel3.setText("direccion *");

        jLabel5.setFont(new java.awt.Font("Harrington", 0, 18));
        jLabel5.setText("Apellido Materno *");

        jLabel7.setFont(new java.awt.Font("Harrington", 0, 18));
        jLabel7.setText("# carnet   *");

        jLabel8.setFont(new java.awt.Font("Harrington", 0, 18));
        jLabel8.setText("Celular");

        jLabel6.setFont(new java.awt.Font("Harrington", 0, 18));
        jLabel6.setText("Correo electronico");

        jLabel2.setFont(new java.awt.Font("Harrington", 0, 18));
        jLabel2.setText("nombre *");

        jLabel1.setFont(new java.awt.Font("Harrington", 0, 18));
        jLabel1.setText("Apellido Paterno  *");

        ApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ApellidoPaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoPaternoKeyTyped(evt);
            }
        });

        TelefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelefonoClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoClienteKeyTyped(evt);
            }
        });

        jButton1.setText("GUARDAR");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreClienteActionPerformed(evt);
            }
        });
        NombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreClienteKeyTyped(evt);
            }
        });

        CarnetCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarnetClienteActionPerformed(evt);
            }
        });
        CarnetCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CarnetClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CarnetClienteKeyTyped(evt);
            }
        });

        DireccionCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DireccionClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionClienteKeyTyped(evt);
            }
        });

        jButton3.setText("BUSCAR PROFESOR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(79, 79, 79)
                .addComponent(CarnetCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(ApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                .addComponent(ApellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))))
                    .addComponent(jLabel2))
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(DireccionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(EmailCliente))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(CelularCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(TelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jButton3)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CarnetCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailClienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_EmailClienteActionPerformed

    private void EmailClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailClienteKeyPressed
        SaltarDeJtextField(EmailCliente,evt);
        // TODO add your handling code here:
}//GEN-LAST:event_EmailClienteKeyPressed

    private void EmailClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailClienteKeyTyped
        char caracter = evt.getKeyChar();

        if(((caracter < 'A') || (caracter > 'Z'))&&
                ((caracter < 'a') || (caracter > 'z'))&&
                (caracter!='@')&&(caracter!='.')&&(caracter!='-')&&(caracter!='_')&&
                ((caracter < '0') || (caracter > '9'))&&
                ((caracter != KeyEvent.VK_BACK_SPACE))) {

            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_EmailClienteKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hide();
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void ApellidoMaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoMaternoKeyPressed
        SaltarDeJtextField(ApellidoMaterno,evt);
        // TODO add your handling code here:
}//GEN-LAST:event_ApellidoMaternoKeyPressed

    private void ApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoMaternoKeyTyped
        ControlarDatosIngresados(evt);
        // TODO add your handling code here:
}//GEN-LAST:event_ApellidoMaternoKeyTyped

    private void CelularClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularClienteKeyTyped
        ControlarNumerosIngresados(evt);
        // TODO add your handling code here:
}//GEN-LAST:event_CelularClienteKeyTyped

    private void ApellidoPaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoPaternoKeyPressed
        SaltarDeJtextField(ApellidoPaterno,evt);
        // TODO add your handling code here:
}//GEN-LAST:event_ApellidoPaternoKeyPressed

    private void ApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoPaternoKeyTyped
        ControlarDatosIngresados(evt);
        // TODO add your handling code here:
}//GEN-LAST:event_ApellidoPaternoKeyTyped

    private void TelefonoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoClienteKeyPressed
        SaltarDeJtextField(TelefonoCliente,evt);
        // TODO add your handling code here:
}//GEN-LAST:event_TelefonoClienteKeyPressed

    private void TelefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoClienteKeyTyped
        ControlarNumerosIngresados(evt);
        // TODO add your handling code here:
}//GEN-LAST:event_TelefonoClienteKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null,"Profesor editado","EDITAR REGISTRO",JOptionPane.INFORMATION_MESSAGE) ;
        dispose();

        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void NombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreClienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_NombreClienteActionPerformed

    private void NombreClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreClienteKeyPressed
        SaltarDeJtextField(NombreCliente,evt);
        // TODO add your handling code here:
}//GEN-LAST:event_NombreClienteKeyPressed

    private void NombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreClienteKeyTyped
        ControlarDatosIngresados(evt);
        // TODO add your handling code here:
}//GEN-LAST:event_NombreClienteKeyTyped

    private void CarnetClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarnetClienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CarnetClienteActionPerformed

    private void CarnetClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CarnetClienteKeyPressed

        SaltarDeJtextField(CarnetCliente,evt);

        // TODO add your handling code here:
}//GEN-LAST:event_CarnetClienteKeyPressed

    private void CarnetClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CarnetClienteKeyTyped
        ControlarNumerosIngresados(evt);
        // TODO add your handling code here:
}//GEN-LAST:event_CarnetClienteKeyTyped

    private void DireccionClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionClienteKeyPressed
        SaltarDeJtextField(DireccionCliente,evt);
        // TODO add your handling code here:
}//GEN-LAST:event_DireccionClienteKeyPressed

    private void DireccionClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionClienteKeyTyped

        // TODO add your handling code here:
}//GEN-LAST:event_DireccionClienteKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        BuscarProfesor buscarprofesor=new BuscarProfesor(this,true);
        buscarprofesor.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
public void ControlarDatosIngresados(java.awt.event.KeyEvent ev)
    {   char espacio=' ';
        char caracter = ev.getKeyChar();


        if( ((caracter < 'A') || (caracter > 'Z'))&&(caracter !=espacio)){

              ev.setKeyChar((char)KeyEvent.VK_CLEAR);
              // ignorar el evento de teclado
         }
    }
    public void ControlarNumerosIngresados(java.awt.event.KeyEvent ev)
    {
        char caracter = ev.getKeyChar();
        if(((caracter < '0') || (caracter > '9')) &&
            (caracter != KeyEvent.VK_BACK_SPACE)){
              ev.setKeyChar((char)KeyEvent.VK_CLEAR);// ignorar el evento de teclado
         }
    }
    public void SaltarDeJtextField(javax.swing.JTextField nombre,java.awt.event.KeyEvent ev)
    {
              nombre.nextFocus();
    }
    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarProfesor dialog = new ModificarProfesor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoMaterno;
    private javax.swing.JTextField ApellidoPaterno;
    private javax.swing.JTextField CarnetCliente;
    private javax.swing.JTextField CelularCliente;
    private javax.swing.JTextField DireccionCliente;
    private javax.swing.JTextField EmailCliente;
    private javax.swing.JTextField NombreCliente;
    private javax.swing.JTextField TelefonoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
