/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VerModulo.java
 *
 * Created on Oct 14, 2011, 12:41:14 AM
 */

package interfaces;

import Entidades.Modulo;

/**
 *
 * @author General
 */
public class VerModulo extends javax.swing.JDialog {
    private Modulo modulo;

    /** Creates new form VerModulo */
    public VerModulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destinadoA = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        fechaInicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fechaFin = new javax.swing.JTextField();
        nivelModulo = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidadClases = new javax.swing.JTextField();
        subNivelModulo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tipoModulo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        costoModulo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        destinadoA.setBackground(new java.awt.Color(204, 204, 255));
        destinadoA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NIÑOS(Mâuschen)", "NIÑOS(KiKu)", "JOVENES", "ADULTOS" }));
        destinadoA.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel8.setText("Destinado a:");

        fechaInicio.setEditable(false);

        jLabel2.setText("Fecha Inicio");

        fechaFin.setEditable(false);

        nivelModulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A1", "A2", "B1", "B2", "C1" }));
        nivelModulo.setEnabled(false);

        jButton3.setText("BUSCAR MODULO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel9.setText("Costo");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel3.setText("Nivel del modulo");

        cantidadClases.setDocument(new JTextFieldLimit(3));
        cantidadClases.setEditable(false);
        cantidadClases.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadClasesKeyTyped(evt);
            }
        });

        subNivelModulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "1+", "2+", "3+", "4+" }));
        subNivelModulo.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel4.setText("Tipo del modulo");

        tipoModulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CURSO REGULAR", "CURSO EXTENSIVO", "CURSO PARTICULAR" }));
        tipoModulo.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel1.setText("Curso");

        costoModulo.setEditable(false);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel5.setText("Cantidad de clases");

        jLabel6.setText("Fecha Fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jButton3)
                .addContainerGap(345, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(nivelModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jLabel6))
                        .addGap(63, 63, 63)
                        .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subNivelModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(307, 307, 307))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(cantidadClases, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(destinadoA, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipoModulo, javax.swing.GroupLayout.Alignment.LEADING, 0, 139, Short.MAX_VALUE))))
                        .addGap(31, 31, 31)
                        .addComponent(costoModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivelModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subNivelModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinadoA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantidadClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(costoModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        BuscarModulo buscarmodulo=new BuscarModulo(this,true);
        buscarmodulo.setVisible(true);

        modulo=buscarmodulo.modulo;

        fechaInicio.setText(modulo.getfechaInicio());
        fechaFin.setText(modulo.getfechaFin());
        costoModulo.setText(String.valueOf(modulo.getCosto()));

        cantidadClases.setText(String.valueOf(modulo.getcantidadClases()));
        //sub nivel
        if(modulo.getsubNivel().equals("1"))
            subNivelModulo.setSelectedIndex(0);
        if(modulo.getsubNivel().equals("2"))
            subNivelModulo.setSelectedIndex(1);
        if(modulo.getsubNivel().equals("3"))
            subNivelModulo.setSelectedIndex(2);
        if(modulo.getsubNivel().equals("4"))
            subNivelModulo.setSelectedIndex(3);
        if(modulo.getsubNivel().equals("1+"))
            subNivelModulo.setSelectedIndex(4);
        if(modulo.getsubNivel().equals("2+"))
            subNivelModulo.setSelectedIndex(5);
        if(modulo.getsubNivel().equals("3+"))
            subNivelModulo.setSelectedIndex(6);
        if(modulo.getsubNivel().equals("4+"))
            subNivelModulo.setSelectedIndex(7);
        //nivel
        if(modulo.getNivel().equals("A1"))
            nivelModulo.setSelectedIndex(0);
        if(modulo.getNivel().equals("A2"))
            nivelModulo.setSelectedIndex(1);
        if(modulo.getNivel().equals("B1"))
            nivelModulo.setSelectedIndex(2);
        if(modulo.getNivel().equals("B2"))
            nivelModulo.setSelectedIndex(3);
        if(modulo.getNivel().equals("C1"))
            nivelModulo.setSelectedIndex(4);
        // TIPO MODULO

        if(modulo.getTipoModulo().equals("CURSO REGULAR"))
            tipoModulo.setSelectedIndex(0);
        if(modulo.getTipoModulo().equals("CURSO  EXTENSIVO"))
            tipoModulo.setSelectedIndex(1);
        if(modulo.getTipoModulo().equals("CURSO  PARTICULAR"))
            tipoModulo.setSelectedIndex(2);
        // tipo (destinado a)

        if(modulo.gettipo().equals("NIÑOS(Mâuschen)"))
            destinadoA.setSelectedIndex(0);
        if(modulo.gettipo().equals("NIÑOS(KiKu)"))
            destinadoA.setSelectedIndex(1);
        if(modulo.gettipo().equals("JOVENES"))
            destinadoA.setSelectedIndex(2);
        if(modulo.gettipo().equals("ADULTOS"))
            destinadoA.setSelectedIndex(3);
}//GEN-LAST:event_jButton3ActionPerformed

    private void cantidadClasesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadClasesKeyTyped
        // TODO add your handling code here:
        //    ControlarNumerosIngresados(evt);
}//GEN-LAST:event_cantidadClasesKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerModulo dialog = new VerModulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadClases;
    private javax.swing.JTextField costoModulo;
    private javax.swing.JComboBox destinadoA;
    private javax.swing.JTextField fechaFin;
    private javax.swing.JTextField fechaInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox nivelModulo;
    private javax.swing.JComboBox subNivelModulo;
    private javax.swing.JComboBox tipoModulo;
    // End of variables declaration//GEN-END:variables

}
